#!/usr/bin/env node
/**
 * Generates a rich markdown summary for GitHub Actions Step Summary.
 * Reads test-results/junit.xml and writes to $GITHUB_STEP_SUMMARY.
 */

import { readFileSync, appendFileSync } from 'node:fs';

const xml = readFileSync('test-results/junit.xml', 'utf8');

// Parse testsuite-level stats
const suiteTag = (xml.match(/<testsuite[^>]+>/) || [''])[0];
const attr = (name) => {
  const m = suiteTag.match(new RegExp(`${name}="([^"]+)"`));
  return m ? parseFloat(m[1]) : 0;
};

const total    = attr('tests');
const failures = attr('failures') + attr('errors');
const skipped  = attr('skipped');
const passed   = total - failures - skipped;
const durationS = attr('time');

// Parse individual testcases
const tests = [];
const re = /<testcase([^>]+)>([\s\S]*?)<\/testcase>|<testcase([^\/][^>]*)\/>/g;
let m;
while ((m = re.exec(xml)) !== null) {
  const attrs = m[1] ?? m[3] ?? '';
  const body  = m[2] ?? '';
  const name  = (attrs.match(/name="([^"]+)"/) ?? [])[1] ?? '';
  const ms    = Math.round(parseFloat((attrs.match(/time="([^"]+)"/) ?? [])[1] ?? '0') * 1000);

  let icon, label;
  if (body.includes('<failure') || body.includes('<error')) {
    icon = '❌'; label = 'Failed';
  } else if (body.includes('<skipped')) {
    icon = '⏭️'; label = 'Skipped';
  } else {
    icon = '✅'; label = 'Passed';
  }

  tests.push({ name, icon, label, ms });
}

// Build markdown
const overallIcon = failures > 0 ? '❌' : '✅';

let md = `# ${overallIcon} API Test Results\n\n`;

// Summary cards
md += `| | Count |\n`;
md += `|:---|:---:|\n`;
md += `| ✅ **Passed**  | \`${passed}\`  |\n`;
md += `| ❌ **Failed**  | \`${failures}\` |\n`;
md += `| ⏭️ **Skipped** | \`${skipped}\` |\n`;
md += `| 📊 **Total**   | \`${total}\`   |\n`;
md += `| ⏱️ **Duration**| \`${durationS}s\` |\n\n`;

// Detailed table
md += `---\n\n`;
md += `### Test Details\n\n`;
md += `| Result | Test | Duration |\n`;
md += `|:------:|:-----|:--------:|\n`;

for (const t of tests) {
  md += `| ${t.icon} | ${t.name} | \`${t.ms}ms\` |\n`;
}

md += `\n---\n*Generated by [jsonplaceholder-api-tests](https://github.com/qa-riccardo/jsonplaceholder-api-tests)*\n`;

// Write to GitHub Step Summary or stdout
const summaryFile = process.env.GITHUB_STEP_SUMMARY;
if (summaryFile) {
  appendFileSync(summaryFile, md);
  console.log('✅ Summary written to GitHub Step Summary.');
} else {
  console.log(md);
}
