#!/usr/bin/env node
/**
 * Generates a rich markdown summary for GitHub Actions Step Summary.
 * Uses the same parsing approach as generate-report.js.
 */

import { readFileSync, appendFileSync } from 'node:fs';

const xml = readFileSync('test-results/junit.xml', 'utf8');

// --- Stats from XML comments written by Node's test runner ---
const total    = parseInt((xml.match(/<!--\s*tests (\d+)/)       || [])[1] || '0');
const passed   = parseInt((xml.match(/<!--\s*pass (\d+)/)        || [])[1] || '0');
const failed   = parseInt((xml.match(/<!--\s*fail (\d+)/)        || [])[1] || '0');
const skipped  = parseInt((xml.match(/<!--\s*skipped (\d+)/)     || [])[1] || '0');
const duration = parseFloat((xml.match(/<!--\s*duration_ms ([\d.]+)/) || [])[1] || '0');

// --- Parse individual testcases (split approach, safe with ">" in names) ---
const tests = [];
for (const block of xml.split(/(?=<testcase[\s>])/)) {
  if (!block.trimStart().startsWith('<testcase')) continue;

  const name = (block.match(/\bname="([^"]*)"/) || [])[1] || '';
  const time = parseFloat((block.match(/\btime="([^"]*)"/) || [])[1] || '0');
  const ms   = Math.round(time * 1000);

  let icon, label;
  if (/<failure/.test(block) || /<error/.test(block)) {
    icon = '❌'; label = 'Failed';
  } else if (/<skipped/.test(block)) {
    icon = '⏭️'; label = 'Skipped';
  } else {
    icon = '✅'; label = 'Passed';
  }

  tests.push({ name, icon, label, ms });
}

// --- Build markdown ---
const overallIcon = failed > 0 ? '❌' : '✅';
const passRate    = total > 0 ? Math.round((passed / total) * 100) : 0;

let md = `# ${overallIcon} API Test Results\n\n`;

md += `| | Count |\n`;
md += `|:---|:---:|\n`;
md += `| ✅ **Passed**   | \`${passed}\` |\n`;
md += `| ❌ **Failed**   | \`${failed}\` |\n`;
md += `| ⏭️ **Skipped**  | \`${skipped}\` |\n`;
md += `| 📊 **Total**    | \`${total}\` |\n`;
md += `| 🎯 **Pass rate**| \`${passRate}%\` |\n`;
md += `| ⏱️ **Duration** | \`${(duration / 1000).toFixed(2)}s\` |\n\n`;

md += `---\n\n### Test Details\n\n`;
md += `| Result | Test | Duration |\n`;
md += `|:------:|:-----|:--------:|\n`;

for (const t of tests) {
  md += `| ${t.icon} | ${t.name} | \`${t.ms}ms\` |\n`;
}

md += `\n---\n*Generated by [jsonplaceholder-api-tests](https://github.com/qa-riccardo/jsonplaceholder-api-tests)*\n`;

// --- Write to GitHub Step Summary or stdout ---
const summaryFile = process.env.GITHUB_STEP_SUMMARY;
if (summaryFile) {
  appendFileSync(summaryFile, md);
  console.log('✅ Summary written to GitHub Step Summary.');
} else {
  console.log(md);
}
